### ISSUE TITLE
EVM <-> SCILLA hardhat tests run very very slow

### ISSUE THREAD

**Issue by PurrProof** [Zilliqa/zq2#1500] opened 2024-09-24 13:00 UTC
**🧐 Issue Summary**

When setting up ZQ2 from [Zilliqa ZQ2 repo](https://github.com/Zilliqa/zq2) using `docker-compose up -d`, the containers run successfully. However, there is an issue with the Hardhat tests from `evm_scilla_js_tests` being extremely slow during execution, like `13538ms`, `8957ms`, `4086ms`.

When testing on the ZQ2 isolated server, speed is the same (very slow):

```shell
RUST_LOG=zilliqa=warn,zilliqa=info ./target/debug/zilliqa 65d7f4da9bedc8fb79cbf6722342960bbdfb9759bc0d9e3fb4989e831ccbc227 -c config-single-node.toml > /tmp/zil_log_out.txt 2>&1 &
```

**📝 Docker Setup and Output**

Containers after running `docker-compose up -d`:

```shell
CONTAINER ID   IMAGE                                                                          COMMAND                  CREATED         STATUS         PORTS                              NAMES
6953ddc66b0b   asia-docker.pkg.dev/prj-p-devops-services-tvwmrf63/zilliqa/eth-spout:v1.3.72   "/eth-spout"             6 minutes ago   Up 6 minutes   0.0.0.0:5200->80/tcp               zq2-faucet-1
667b367c1cef   zilliqa/otterscan:develop                                                      "/docker-entrypoint.…"   6 minutes ago   Up 6 minutes   0.0.0.0:5100->80/tcp               zq2-otterscan-1
c69471e002c1   zq2-node0                                                                      "/run.sh 56d7a450d75…"   6 minutes ago   Up 6 minutes                                      zilliqanode2
c8a1f59056e6   grafana/grafana-oss:latest                                                     "/run.sh"                6 minutes ago   Up 6 minutes   0.0.0.0:3000->3000/tcp             zq2-grafana-1
59869b0da8f1   otel/opentelemetry-collector:latest                                            "/otelcol --config=/…"   6 minutes ago   Up 6 minutes   4317/tcp, 55678-55679/tcp          zq2-otel-collector-1
5e4fc27950f6   zq2-node0                                                                      "/run.sh 65d7f4da9be…"   6 minutes ago   Up 6 minutes   0.0.0.0:4201->4201/tcp             zilliqanode0
b112031c2963   zq2-node0                                                                      "/run.sh 62070b1a3b5…"   6 minutes ago   Up 6 minutes                                      zilliqanode1
e2c2e7e88c25   grafana/mimir:latest                                                           "/bin/mimir ./mimir …"   6 minutes ago   Up 6 minutes   8080/tcp, 0.0.0.0:9009->9009/tcp   zq2-mimir-1
94f5b31c6103   zq2-node0                                                                      "/run.sh db670cbff28…"   6 minutes ago   Up 6 minutes                                      zilliqanode3
```

**📝 Hardhat Balances Output**

Checking balances after setting up containers using `pnpm hardhat balances --zil` and `pnpm hardhat balances --eth`:

```shell
: zq2/evm_scilla_js_tests$ pnpm hardhat balances --zil
WARNING: You are currently using Node.js v16.0.0, which is not supported by Hardhat. This can lead to unexpected behavior. See https://hardhat.org/nodejs-versions

2) 0x8D393a22E4476fF8212DE13fE1939De2a236F0A7  Balance: 5000 zil
3) 0x9cB422D2Fabe9622ed706ad5D9d3fFd2cDd1C001  Balance: 5000 zil
4) 0xAcE5F1e883d3e02A1b2C78F6909a8C0430C6Fb12  Balance: 5000 zil

: zq2/evm_scilla_js_tests$ pnpm hardhat balances --eth
WARNING: You are currently using Node.js v16.0.0, which is not supported by Hardhat. This can lead to unexpected behavior. See https://hardhat.org/nodejs-versions

Eth balances
1) 0x2b5ad5c4795c026514f8317c7a215e218dccd6cf  Balance: 6423.134709348887199932 ether
2) 0x6813eb9362372eef6200f3b1dbc3f819671cba69  Balance: 6492.222222222222222152 ether
3) 0x1eff47bc3a10a45d4b230b5d10e37751fe6aa718  Balance: 6588.108893624552688814 ether
```

**📝 Test Execution Output**

Executing Hardhat tests with `pnpm hardhat test` reveals that the tests work but are very slow, like `13538ms`, `8957ms`, `4086ms`.

```shell
: zq2/evm_scilla_js_tests$ pnpm hardhat test
Secp256k1 bindings are not compiled. Pure JS implementation will be used.
⚠️  Your Eth/Zil accounts supposed to have funds to run tests successfully.
Scilla Contracts:
Nothing changed since last compile.

  Assure funds in contract accounts are adequate
    ✔ Should exist and have enough funds

  BasicInterop
    - Should be deployed successfully
    - It should return revert while reading non-existing  field
    - It should return 0 while reading non-existing key in simpleMap
    - It should return 0 while reading non-existing key in nestedMap
    When call is performed from solidity to scilla contract
      - It should return proper string after invoking set method with string arg
      - It should return proper integer after invoking set method for simpleMap
      - It should return proper integer after invoking set method for nestedMap
      - It should return proper unsigned integer after invoking set method with integer arg
      - It should return proper integer after invoking set method with integer arg
      - It should return proper address after invoking set method with address arg
      - It should return proper unsigned integer value for an immutable field
      - It should return proper integer value for an immutable field
      - It should return proper string value for an immutable field
      - It should return proper address value for an immutable field
      - Should fail to read uint if field name is not available
      - Should fail to read uint if contract address is not valid

  Blockchain Instructions contract #parallel
    ✔ Should be deployed successfully @block-1
    ✔ Should return the owner address when getOrigin function is called @block-1

  Chained Contract Calls Functionality #parallel
    Install and call chained contracts @block-1
      - Should create a transaction trace after child creation
      ✔ Should correctly call chained contracts @block-2 (13538ms)

  Revert Contract Call
    ✔ Will revert the transaction when revert is called
    ✔ Should revert transaction with a custom message if the called function reverts with custom message
    ✔ Should not be reverted despite its child possibly reverting (8957ms)

    ✔ Should be reverted without any reason if specified gasLimit is not enough to complete txn (4086ms)

  Create2 instruction #parallel
    ✔ Should predict and deploy create2 contract @block-1 (4166ms)

  Delegatecall functionality #parallel
    ✔ should delegate function call correctly @block-1 (4380ms)
```

**📝 Additional Info**

- System: Linux Mint 22 Wilma
- Node.js version: v16.0.0
- Kernel: 6.8.0-45-generic arch: x86_64
- Processor: Intel© Core™ i7-3612QM CPU @ 2.10GHz × 4
- Memory: 9.2 GiB

**Comment by JamesHinshelwood** [comment] 2024-09-24 14:13
Hi @PurrProof , thanks for checking out ZQ2 and reporting this!

I had a brief look and I can reproduce similar results. Indeed the tests seem slower than they should be. When staring at the logs, it appears the chain is performing fine (transactions are mined almost instantly) but the tests still sleep for a while between each action. I'm guessing this might be some default hardhat configuration that is tuned to chains with longer block times (i.e. wait a few seconds before trying to poll for a transaction receipt).

@saeed-zil Would you mind looking into what the cause could be?

**Comment by saeed-zil** [comment] 2024-10-02 10:04
The issue lies with the pollingInterval in the current version of ethers.js, which is set to 4 seconds. Initially, attempts to get the receipts result in null, causing ethers.js to wait another 4 seconds before trying again. Unfortunately, there’s no straightforward way to change this interval to something like 200ms in Hardhat, as Hardhat has its own wrapper around ethers.js. We need to update these dependencies to newer versions in the near future. I had some experience with the newer versions of Hardhat and Ethers.js, and the problem was resolved.

**Comment by saeed-zil** [comment] 2024-10-16 05:23
The problem was addressed in https://github.com/Zilliqa/zq2/pull/1568

**Closed by saeed-zil** 2024-10-16 05:23 UTC
