### ISSUE TITLE
Help plz: Invalid signature in simple transaction (golang)

### ISSUE THREAD

**Issue by PurrProof** [Zilliqa/zq2#1502] opened 2024-09-24 17:13 UTC
I've took CreateTransaction golang example from [here](https://dev.zilliqa.com/zilliqa2/api/apis/api/zilliqa/CreateTransaction/)

Here is slightly modified version with better logging, increased gas limit etc:
[main.txt](https://github.com/user-attachments/files/17118115/main.txt)

On the ZQ2 side there is an `invalid signature` error:

```
2024-09-24T17:05:55.222307Z  INFO zilliqa::node: 382: seen new txn Zilliqa { tx: TxZilliqa { chain_id: 1, nonce: 1, gas_price: ZilAmount(2000000016), gas_limit: ScillaGas(50000), to_addr: 0x4baf5fada8e5db92c3d3242618c5b47133ae003c, amount: ZilAmount(10000000), code: "", data: "" }, key: PublicKey { point: AffinePoint { x: FieldElement(FieldElementImpl { value: FieldElement5x52([3388391445012197, 1329098899749562, 1619017321969550, 2206526636033769, 217722622591469]), magnitude: 1, normalized: true }), y: FieldElement(FieldElementImpl { value: FieldElement5x52([1180503181878570, 1780274363765302, 1808606147638834, 3434437250924948, 29555431482941]), magnitude: 1, normalized: true }), infinity: 0 } }, sig: ecdsa::Signature<Secp256k1>(C85D8726480271D0264DBC05A2AAEA256BAD4D355112261D3A6B370244D825F03BE0C450BC38362AB2C0DF221EFE867C7A625380B390EDA59AD1D00B6BBBF6A2) } hash=bcc0c88f2fdd75fe4a0229129a35ef8fa75d9fb01962a4b05e6ee2d232b3506b
2024-09-24T17:05:55.230325Z ERROR zilliqa::api::zil: 40: e=invalid signature
```

Test program output:

```shell
Private Key: 0000000000000000000000000000000000000000000000000000000000000002

Wallet initialized and private key added.

Public Key: 02c6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee5

Address: 8d393a22e4476ff8212de13fe1939de2a236f0a7

Provider initialized with host: http://172.17.0.1:4201

Balance and Nonce:
{
    "balance": "5000000000000000",
    "nonce": 0
}

Minimum Gas Price: 2000000016

Transaction Version (packed): 65537
Transaction Version (string): 65537

Transaction Object:
{
    "ID": "",
    "Version": "65537",
    "Nonce": "1",
    "Amount": "10000000",
    "GasPrice": "2000000016",
    "GasLimit": "50000",
    "Signature": "",
    "Receipt": {
        "accept": false,
        "errors": null,
        "exceptions": null,
        "success": false,
        "cumulative_gas": "",
        "epoch_num": "",
        "event_logs": null,
        "transitions": null
    },
    "SenderPubKey": "02c6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee5",
    "ToAddr": "0x4BAF5faDA8e5Db92C3d3242618c5B47133AE003C",
    "Code": "",
    "Data": "",
    "Status": 0,
    "ContractAddress": "",
    "Priority": false
}

Transaction signed successfully.

Signed Transaction:
{
    "ID": "",
    "Version": "65537",
    "Nonce": "1",
    "Amount": "10000000",
    "GasPrice": "2000000016",
    "GasLimit": "50000",
    "Signature": "c85d8726480271d0264dbc05a2aaea256bad4d355112261d3a6b370244d825f03be0c450bc38362ab2c0df221efe867c7a625380b390eda59ad1d00b6bbbf6a2",
    "Receipt": {
        "accept": false,
        "errors": null,
        "exceptions": null,
        "success": false,
        "cumulative_gas": "",
        "epoch_num": "",
        "event_logs": null,
        "transitions": null
    },
    "SenderPubKey": "02c6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee5",
    "ToAddr": "0x4BAF5faDA8e5Db92C3d3242618c5B47133AE003C",
    "Code": "",
    "Data": "",
    "Status": 0,
    "ContractAddress": "",
    "Priority": false
}

Transaction error: invalid signature
```

**Comment by PurrProof** [comment] 2024-09-26 13:57
For JS-version I just use `pnpm hardhat transfer --amount 1 --from 0000000000000000000000000000000000000000000000000000000000000002 --to 0x4BAF5faDA8e5Db92C3d3242618c5B47133AE003C --from-address-type zil` and check generated tx in `mitmproxy`.

For Golang, I use `https://github.com/Zilliqa/gozilliqa-sdk` and the code from [this](https://dev.zilliqa.com/zilliqa2/api/apis/api/zilliqa/CreateTransaction) golang example.

**JS**

```json
{
    "id": 1,
    "jsonrpc": "2.0",
    "method": "CreateTransaction",
    "params": [
        {
            "amount": "1000000000000",
            "code": "",
            "data": "",
            "gasLimit": "2100",
            "gasPrice": "2000000000",
            "nonce": 4,
            "priority": false,
            "pubKey": "02c6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee5",
            "signature": "28213537457575af768024506fa18ea5a4e660bc17fad81888e6d447b8c75badfdec3964135516ff91060906defaccc47ac468bc65bbf4cfb450bc3d1aeb15d4",
            "toAddr": "0x4BAF5faDA8e5Db92C3d3242618c5B47133AE003C",
            "version": 65537
        }
    ]
}
```

**GOLANG**

```json
{
    "id": 0,
    "jsonrpc": "2.0",
    "method": "CreateTransaction",
    "params": [
        {
            "amount": "10000000",
            "code": "",
            "data": "",
            "gasLimit": "50000",
            "gasPrice": "2000000016",
            "nonce": 5,
            "priority": false,
            "pubKey": "02c6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee5",
            "signature": "8a361da49ec974a28c6a018bbc2591b560bc2111b5900b4b27a8f1c1091b06ea1587c92a6d8cd5f69d762dc841b3b74daf3d6f6aa8978f86e2a761fc14f2b98e",
            "toAddr": "4BAF5faDA8e5Db92C3d3242618c5B47133AE003C",
            "version": 65537
        }
    ]
}
```

**ZQ2 log:**

```
{ tx: TxZilliqa 
    { chain_id: 1, nonce: 6, gas_price: ZilAmount(2000000000), 
    gas_limit: ScillaGas(2100), 
    to_addr: 0x4baf5fada8e5db92c3d3242618c5b47133ae003c, 
    amount: ZilAmount(1000000000000), code: "", data: "" },
    key: PublicKey { point: AffinePoint { x: FieldElement(FieldElementImpl
    { value: FieldElement5x52([3388391445012197, 1329098899749562, 1619017321969550, 2206526636033769, 217722622591469]),
    magnitude: 1, normalized: true }),
    y: FieldElement(FieldElementImpl
        { value: FieldElement5x52([1180503181878570, 1780274363765302, 1808606147638834, 3434437250924948, 29555431482941]),
        magnitude: 1, normalized: true }),
        infinity: 0 }
    },
    sig: ecdsa::Signature<Secp256k1>(B696574DB4BEA820EA8F33AF64BCCF72C9C54868A30B09505517049B12357D559F652CB2BFB3D79F50AA8ED693D1CF32BFAF5D4FF0B5EF75FC4F37499069C437) }

2024-09-26T12:06:26.048968Z  INFO zilliqa::exec: 563: executing txn hash=.......    
    
    
    
{ tx: TxZilliqa 
    { chain_id: 1, nonce: 7, gas_price: ZilAmount(2000000016), 
    gas_limit: ScillaGas(50000), 
    to_addr: 0x4baf5fada8e5db92c3d3242618c5b47133ae003c, 
    amount: ZilAmount(10000000), code: "", data: "" },
    key: PublicKey { point: AffinePoint { x: FieldElement(FieldElementImpl
    { value: FieldElement5x52([3388391445012197, 1329098899749562, 1619017321969550, 2206526636033769, 217722622591469]),
    magnitude: 1, normalized: true }),
    y: FieldElement(FieldElementImpl
        { value: FieldElement5x52([1180503181878570, 1780274363765302, 1808606147638834, 3434437250924948, 29555431482941]),
        magnitude: 1, normalized: true }),
        infinity: 0 }
    },
    sig: ecdsa::Signature<Secp256k1>(1AFB3391D77F7CB2D433CFF631A77D15543387E22080583F3764F5300524834A721BDB73E1502B1651CD6D1E3B4C8D4083803920DEB969EB74DCBF6359C00ECD) }
    
    2024-09-26T13:32:32.109930Z ERROR zilliqa::api::zil: 40: e=invalid signature
  ```

**Comment by rrw-zilliqa** [comment] 2024-10-04 17:37
Thank you for the report!

Reproduced at https://github.com/rrw-zilliqa/zq2-1502 - looks like a maths error; both zq1 testnet and zq2 return a signing failure, in zq2 it comes from schnorr::verify().  Will continue to investigate.

**Comment by rrw-zilliqa** [comment] 2024-10-08 09:49
This turns out to be a bug in gozilliqa-sdk - https://github.com/Zilliqa/gozilliqa-sdk/issues/120 ; I've filed a PR there.
It also exposed an internal panic!() when you submit a zilliqa txn to zq2 with nonce = 0, which is fixed in the above PR (it now returns an error message, as Zilliqa 1 does).

The sample code in https://github.com/rrw-zilliqa/zq2-1502 works for me on both ZQ1 and ZQ2 with the fixed gozilliqa-sdk; could you retest please and reopen this issue if you find that it doesn't work for you?

Thanks!

**Comment by rrw-zilliqa** [comment] 2024-10-08 11:32
Closing since the related gozilliqa-sdk issue has a fix now. Please reopen if you continue to have problems and thanks again for the report!

**Closed by rrw-zilliqa** 2024-10-08 11:32 UTC

**Comment by PurrProof** [comment] 2024-10-10 17:10
Thank you!
It works now.

**Comment by rrw-zilliqa** [comment] 2024-10-23 08:39
Awesome :-) - glad it helped and thank you for letting us know!
