### ISSUE TITLE
Scilla external libray deployment fails on zq2prototestnet.

### ISSUE THREAD

**Issue by chetan-zilliqa** [Zilliqa/zq2#1238] opened 2024-07-31 04:36 UTC
I ran the scilla UserDefined library tests on zq2 prototestnet network using the EvmAcceptanceTests of the zq1 directory. But it fails with a revert message.

`Fail with revert message: 'Following the library definition, a contract is expected. '`

```npx hardhat test test/scilla/UserDefinedLibrary.ts --network zq2_prototestnet```

https://explorer.zq2-prototestnet.zilliqa.com/tx/0x37b88e8d0070067e879007c848ff5da05b2b6f7195a7d250ef24749548802579

**Comment by saeed-zil** [comment] 2024-09-23 10:29
Duplicate of #1295

**Closed by saeed-zil** 2024-09-23 10:29 UTC
Labels: duplicate
