### ISSUE TITLE
Otterscan's DS block view doesn't work against zq2

### ISSUE THREAD

**Issue by rrw-zilliqa** [Zilliqa/zq2#882] opened 2024-05-02 13:00 UTC
.. partly because of the wrong field names in BlockChainInfo, partly because GetDsBlock is not yet implemented.

**Comment by DrZoltanFazekas** [comment] 2024-05-27 14:30
we'll remove the DS block list and only show TX blocks for now

**Comment by yaron-zilliqa** [comment] 2024-05-27 14:34
Duplicate of https://github.com/Zilliqa/otterscan/issues/39

**Closed by yaron-zilliqa** 2024-05-27 14:34 UTC
