### ISSUE TITLE
Implement GetSmartContractSubState API 

### ISSUE THREAD

**Issue by chetan-zilliqa** [Zilliqa/zq2#1588] opened 2024-10-08 06:02 UTC
`GetSmartContractSubState` allows us to return the substate, variable or structure of a large subset. The API is not currently supported.

for eg:
```
curl --request POST \
  --url http://localhost:4201/ \
  --header 'Content-Type: application/json' \
  --data '{
    "id": "1",
    "jsonrpc": "2.0",
    "method": "GetSmartContractSubState",
	"params": ["zil15tjx2l0gzzxaxucwk50stgw5smthhckl8qcqmf","bnum_req", []]
}'
```

**Comment by chetan-zilliqa** [comment] 2024-10-08 06:02
cc @DrZoltanFazekas @bzawisto @JamesHinshelwood

**Comment by saeed-zil** [comment] 2024-10-08 14:23
@chetan-zilliqa Isn't a duplicate of https://github.com/Zilliqa/zq2/issues/1545

**Comment by JamesHinshelwood** [comment] 2024-10-08 15:03
Duplicate of #1545

**Closed by JamesHinshelwood** 2024-10-08 15:03 UTC

**Comment by chetan-zilliqa** [comment] 2024-10-09 05:18
oh yeah, sorry,  I should have checked before. Thanks @saeed-zil and @JamesHinshelwood
